### ISSUE TITLE
Technical Review?

### ISSUE THREAD

**Issue by NathanWalker** [btroncone/ngrx-examples#1]
Hi guys,

Your examples here have been extremely helpful in understanding how to setup `ngrx/store` in an application. I'm still learning but I have just pushed an integration here:

The relevant pieces are here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/i18n.framework/state/multilingual.reducer.ts
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/i18n.framework/state/multilingual.actions.ts
Usage here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/i18n.framework/components/lang-switcher.component.ts

Another reducer here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/core.framework/state/route.reducer.ts
Usage here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/frameworks/core.framework/common/route-common.component.ts

Combining others with those here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/main.web.ts#L26-L30

Curious if maybe I should follow the examples here:
https://github.com/ngrx/angular2-store-example

Whenever you get a chance, I would greatly appreciate your feedback.
Does this look like a good integration based on your understandings?
Thank you so much.

**Comment by btroncone** [comment]
No problem, I'll take a look and let you know a bit later today. Thanks for the interest!

**Comment by btroncone** [comment]
A couple things I noticed:

1.) You generally will not need to call combine reducers, provideStore will combine reducers behind the scenes when you pass an object map of reducers.
2.) For storing route state, you can check out this [middleware](https://www.npmjs.com/package/ngrx-store-devtools-next).
3.) It looks like you may be maintaining seperate state in one of your services (based on this call `this.multilang.changeLang(action.payload.lang)`). It would be better to move all state up to store and `dispatch` an action to update language state.
4.) Since your action service is really dispatching one action, you could dispatch the action from your service method rather then wrapping in a `Subject`. You could even remove the service and inject dispatcher into component for this use-case.
5.) Since 1.3 there is no need to `dispatch` from subscribe like this: `.subscribe((action: Action) => store.dispatch(action));`. Instead, since store is a BehaviorSubject, you can simply subscribe store to your `actions$` stream: `.subscribe(store);`

Just a few thoughts after a cursory glance, I think it looks great! Good luck with your project!

**Comment by NathanWalker** [comment]
Excellent feedback @btroncone Thank you so much for your time looking at it!
This really helps my understanding, I'll make adjustments based on this soon, you're the best!

**Comment by NathanWalker** [comment]
@btroncone One additional question. Curious then where all initial/default state should reside, in `Reducer` or in `Actions` (*if even using an Action service*). Say for something like this:
https://github.com/NathanWalker/angular2-seed-advanced/blob/ngrx-wip/src/frameworks/app.framework/scientists/services/name-list.service.ts#L6-L11

The list of names I presume should be moved to become an instance variable in either of these 2 services?
https://github.com/NathanWalker/angular2-seed-advanced/blob/ngrx-wip/src/frameworks/app.framework/state/scientists.actions.ts
`or ...`
https://github.com/NathanWalker/angular2-seed-advanced/blob/ngrx-wip/src/frameworks/app.framework/state/scientists.reducer.ts

If the answer is the `Reducer`, then how would one deal with services that are needed from DI to fetch an async remote resource like a persisted list from an api? In this case, I feel like initializing state from the `Actions` service would make more sense since services could be injected.

**Comment by btroncone** [comment]
I thought you responded with another question but I do not see it here now. Feel free to message me on gitter at any time if you have additional questions, I don't mind at all!
